In [ ]:
# get data from:
# https://www.ic.polimi.it/open-data-challenge/
# https://www.ic.polimi.it/download/open-data-download/
# remove 'labels.txt' from the DATASETchannllenge folder (these are the feature names)

### Step 1: From many hdf5 files to 1 csv file

#### Imports

In [ ]:
# ! pip install numpy==1.21 --user
# to fix AttributeError: module 'numpy' has no attribute 'typeDict'
# https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict

In [4]:
print(np.__version__) # 1.24.2  # 1.21.0

1.21.0

In [5]:
%matplotlib inline

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import os

import h5py

import zipfile

#### Unzip raw data files (bunch of hd5f data files)

In [6]:
archive = zipfile.ZipFile('./DATASETchallenge.zip')

for file in archive.namelist():
    #if file.startswith('foo/'):
    #    archive.extract(file, 'destination_path')
    archive.extract(file, './data_DATASETchallenge/')

#### Convert from hdf5 to csv

In [8]:
ls_data_hdf5 = os.listdir('./DATASETchallenge')
print(len(ls_data_hdf5))

ls_data_hdf5[0:5] # start count from 1 (not 0) to avoid 'labels.txt'

380

['labels.txt', 'layer1.hdf5', 'layer10.hdf5', 'layer100.hdf5', 'layer101.hdf5']

In [10]:
df_all = []

df_all = pd.DataFrame(columns= ['x', 'y', 'NominalPower', 'NominalSpeed',
                  'NominalSpotDiameter', 'LaserPowerCurrent',
                  'SignalPdInGaAs', 'IDbulkLayer', 'IDoocLayer',
                  'c_1_cost', 'c_2_cost'
                 ])

for i in range(1,len(ls_data_hdf5)):
    print(i)
    #print(ls_data_hdf5[i])
    sample_dataset_object = h5py.File('./DATASETchallenge/' + ls_data_hdf5[i], 'r')
    list(sample_dataset_object.keys())
    sample_dataset = sample_dataset_object['OpenData'][:]
    sample_dataset = sample_dataset.transpose()
    # print(sample_dataset.shape)df = []

    df = pd.DataFrame(sample_dataset)

    df.columns = ['x', 'y', 'NominalPower', 'NominalSpeed',
                  'NominalSpotDiameter', 'LaserPowerCurrent',
                  'SignalPdInGaAs', 'IDbulkLayer', 'IDoocLayer',
                  'c_1_cost', 'c_2_cost'
                 ]
    #print(ls_data_hdf5[i])
    df['file'] = ls_data_hdf5[i]
    #print(df_all.shape)
    df_all = pd.concat([df_all, df])
    print(df_all.shape)

1
(31099, 12)
2
(62187, 12)
3
(93258, 12)
4
(124055, 12)
5
(154817, 12)
6
(185898, 12)
7
(216470, 12)
8
(247581, 12)
9
(278487, 12)
10
(309103, 12)
11
(339834, 12)
12
(370913, 12)
13
(401700, 12)
14
(432704, 12)
15
(463781, 12)
16
(494855, 12)
17
(525756, 12)
18
(556848, 12)
19
(587847, 12)
20
(618598, 12)
21
(649394, 12)
22
(680140, 12)
23
(710781, 12)
24
(741538, 12)
25
(772329, 12)
26
(803433, 12)
27
(834435, 12)
28
(844123, 12)
29
(853798, 12)
30
(863501, 12)
31
(873147, 12)
32
(904126, 12)
33
(934660, 12)
34
(965229, 12)
35
(996301, 12)
36
(1027389, 12)
37
(1058265, 12)
38
(1089107, 12)
39
(1120184, 12)
40
(1150961, 12)
41
(1181368, 12)
42
(1212210, 12)
43
(1243054, 12)
44
(1274119, 12)
45
(1305084, 12)
46
(1335828, 12)
47
(1366916, 12)
48
(1397878, 12)
49
(1428389, 12)
50
(1459462, 12)
51
(1489865, 12)
52
(1520736, 12)
53
(1551566, 12)
54
(1582391, 12)
55
(1613278, 12)
56
(1643773, 12)
57
(1674328, 12)
58
(1705118, 12)
59
(1736205, 12)
60
(1766918, 12)
61
(1797997, 12)
62
(1828654, 12)
63
(1859493, 12)
64
(1890092, 12)
65
(1899771, 12)
66
(1909348, 12)
67
(1919037, 12)
68
(1949951, 12)
69
(1959596, 12)
70
(1969302, 12)
71
(2000375, 12)
72
(2031135, 12)
73
(2062181, 12)
74
(2092542, 12)
75
(2123356, 12)
76
(2154435, 12)
77
(2185507, 12)
78
(2216139, 12)
79
(2246738, 12)
80
(2277679, 12)
81
(2308400, 12)
82
(2339001, 12)
83
(2369850, 12)
84
(2400727, 12)
85
(2431550, 12)
86
(2462562, 12)
87
(2493633, 12)
88
(2524633, 12)
89
(2555748, 12)
90
(2586788, 12)
91
(2617735, 12)
92
(2648074, 12)
93
(2678806, 12)
94
(2709876, 12)
95
(2740946, 12)
96
(2771769, 12)
97
(2802855, 12)
98
(2833664, 12)
99
(2864796, 12)
100
(2895774, 12)
101
(2926828, 12)
102
(2957334, 12)
103
(2988171, 12)
104
(2997859, 12)
105
(3007529, 12)
106
(3017251, 12)
107
(3026914, 12)
108
(3036582, 12)
109
(3046246, 12)
110
(3076960, 12)
111
(3107846, 12)
112
(3138767, 12)
113
(3169828, 12)
114
(3200472, 12)
115
(3231300, 12)
116
(3262393, 12)
117
(3293165, 12)
118
(3324270, 12)
119
(3355234, 12)
120
(3386225, 12)
121
(3417195, 12)
122
(3448072, 12)
123
(3479205, 12)
124
(3510245, 12)
125
(3541146, 12)
126
(3572106, 12)
127
(3603067, 12)
128
(3633863, 12)
129
(3664930, 12)
130
(3695917, 12)
131
(3727004, 12)
132
(3757980, 12)
133
(3788513, 12)
134
(3819254, 12)
135
(3849658, 12)
136
(3880743, 12)
137
(3911597, 12)
138
(3942271, 12)
139
(3973349, 12)
140
(4004097, 12)
141
(4035208, 12)
142
(4066208, 12)
143
(4096703, 12)
144
(4106387, 12)
145
(4116077, 12)
146
(4147076, 12)
147
(4156749, 12)
148
(4166436, 12)
149
(4176130, 12)
150
(4185853, 12)
151
(4195562, 12)
152
(4226475, 12)
153
(4257339, 12)
154
(4288028, 12)
155
(4318858, 12)
156
(4349756, 12)
157
(4380577, 12)
158
(4411436, 12)
159
(4442541, 12)
160
(4473621, 12)
161
(4504350, 12)
162
(4535054, 12)
163
(4565951, 12)
164
(4596485, 12)
165
(4627398, 12)
166
(4658531, 12)
167
(4689337, 12)
168
(4720269, 12)
169
(4751338, 12)
170
(4782293, 12)
171
(4813237, 12)
172
(4844200, 12)
173
(4875046, 12)
174
(4905453, 12)
175
(4936224, 12)
176
(4967319, 12)
177
(4998370, 12)
178
(5029224, 12)
179
(5038894, 12)
180
(5069972, 12)
181
(5100850, 12)
182
(5131242, 12)
183
(5162296, 12)
184
(5192699, 12)
185
(5202365, 12)
186
(5212042, 12)
187
(5221717, 12)
188
(5231406, 12)
189
(5241061, 12)
190
(5271779, 12)
191
(5281462, 12)
192
(5291149, 12)
193
(5300869, 12)
194
(5331863, 12)
195
(5362346, 12)
196
(5393090, 12)
197
(5423840, 12)
198
(5454595, 12)
199
(5485730, 12)
200
(5516803, 12)
201
(5547605, 12)
202
(5578364, 12)
203
(5609219, 12)
204
(5640279, 12)
205
(5671177, 12)
206
(5702257, 12)
207
(5733312, 12)
208
(5763892, 12)
209
(5794972, 12)
210
(5826041, 12)
211
(5856789, 12)
212
(5887204, 12)
213
(5918262, 12)
214
(5949028, 12)
215
(5979505, 12)
216
(6010431, 12)
217
(6040971, 12)
218
(6071880, 12)
219
(6102775, 12)
220
(6133830, 12)
221
(6164749, 12)
222
(6195830, 12)
223
(6226841, 12)
224
(6257594, 12)
225
(6288461, 12)
226
(6319575, 12)
227
(6350309, 12)
228
(6359951, 12)
229
(6369647, 12)
230
(6379354, 12)
231
(6388995, 12)
232
(6398684, 12)
233
(6408244, 12)
234
(6417922, 12)
235
(6449008, 12)
236
(6458627, 12)
237
(6468322, 12)
238
(6499149, 12)
239
(6530117, 12)
240
(6561012, 12)
241
(6592103, 12)
242
(6623147, 12)
243
(6653938, 12)
244
(6684709, 12)
245
(6715694, 12)
246
(6746404, 12)
247
(6776971, 12)
248
(6807868, 12)
249
(6838976, 12)
250
(6869746, 12)
251
(6900849, 12)
252
(6931894, 12)
253
(6962760, 12)
254
(6993630, 12)
255
(7024424, 12)
256
(7055501, 12)
257
(7086587, 12)
258
(7117428, 12)
259
(7148528, 12)
260
(7179414, 12)
261
(7210342, 12)
262
(7241417, 12)
263
(7272486, 12)
264
(7303573, 12)
265
(7334630, 12)
266
(7365161, 12)
267
(7395718, 12)
268
(7426479, 12)
269
(7457564, 12)
270
(7488519, 12)
271
(7498187, 12)
272
(7507849, 12)
273
(7517569, 12)
274
(7527221, 12)
275
(7536889, 12)
276
(7546539, 12)
277
(7556230, 12)
278
(7565907, 12)
279
(7596815, 12)
280
(7606478, 12)
281
(7616165, 12)
282
(7647246, 12)
283
(7678026, 12)
284
(7709128, 12)
285
(7739967, 12)
286
(7770950, 12)
287
(7801566, 12)
288
(7832481, 12)
289
(7863553, 12)
290
(7894092, 12)
291
(7925040, 12)
292
(7956137, 12)
293
(7987212, 12)
294
(8017810, 12)
295
(8048623, 12)
296
(8079440, 12)
297
(8109943, 12)
298
(8140783, 12)
299
(8171917, 12)
300
(8202792, 12)
301
(8233702, 12)
302
(8264786, 12)
303
(8295838, 12)
304
(8326872, 12)
305
(8357693, 12)
306
(8388621, 12)
307
(8419736, 12)
308
(8450487, 12)
309
(8481569, 12)
310
(8512558, 12)
311
(8543306, 12)
312
(8574390, 12)
313
(8605365, 12)
314
(8636037, 12)
315
(8666577, 12)
316
(8697612, 12)
317
(8728604, 12)
318
(8759237, 12)
319
(8790217, 12)
320
(8820770, 12)
321
(8851648, 12)
322
(8882754, 12)
323
(8913771, 12)
324
(8944412, 12)
325
(8975480, 12)
326
(9006306, 12)
327
(9037031, 12)
328
(9067978, 12)
329
(9098774, 12)
330
(9129866, 12)
331
(9160620, 12)
332
(9191697, 12)
333
(9222691, 12)
334
(9232366, 12)
335
(9242015, 12)
336
(9272877, 12)
337
(9303890, 12)
338
(9334445, 12)
339
(9365215, 12)
340
(9396201, 12)
341
(9427268, 12)
342
(9458001, 12)
343
(9489075, 12)
344
(9519811, 12)
345
(9550895, 12)
346
(9581929, 12)
347
(9612986, 12)
348
(9643515, 12)
349
(9674456, 12)
350
(9705483, 12)
351
(9736165, 12)
352
(9767199, 12)
353
(9798306, 12)
354
(9829190, 12)
355
(9860268, 12)
356
(9890977, 12)
357
(9921761, 12)
358
(9952297, 12)
359
(9983062, 12)
360
(10013798, 12)
361
(10044906, 12)
362
(10075676, 12)
363
(10106790, 12)
364
(10137680, 12)
365
(10168752, 12)
366
(10199837, 12)
367
(10230798, 12)
368
(10261894, 12)
369
(10292640, 12)
370
(10302312, 12)
371
(10311929, 12)
372
(10321655, 12)
373
(10352317, 12)
374
(10383379, 12)
375
(10414285, 12)
376
(10445360, 12)
377
(10476279, 12)
378
(10506813, 12)
379
(10537388, 12)

In [11]:
df_all = df_all.reset_index(drop=True)

In [12]:
display(df_all.head())
display(df_all.tail())

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file
0,-18.487875,-80.184509,4800.0,1500.0,100.0,0.0,166.0,1.0,0.0,0.0,20.0,layer1.hdf5
1,-18.487875,-80.191986,4800.0,1500.0,100.0,1536.0,214.0,1.0,0.0,0.0,20.0,layer1.hdf5
2,-18.487125,-80.203217,4800.0,1500.0,100.0,3421.0,509.0,1.0,0.0,0.0,20.0,layer1.hdf5
3,-18.486378,-80.217072,4800.0,1500.0,100.0,4051.0,738.0,1.0,0.0,0.0,20.0,layer1.hdf5
4,-18.485628,-80.231659,4800.0,1500.0,100.0,4310.0,856.0,1.0,0.0,0.0,20.0,layer1.hdf5

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file
10537383,-25.804117,-89.448349,4800.0,1500.0,100.0,4506.0,989.0,1.0,0.0,0.0,20.0,layer99.hdf5
10537384,-25.813473,-89.458084,4800.0,1500.0,100.0,4507.0,973.0,1.0,0.0,0.0,20.0,layer99.hdf5
10537385,-25.821707,-89.466316,4800.0,1500.0,100.0,4506.0,989.0,1.0,0.0,0.0,20.0,layer99.hdf5
10537386,-25.827694,-89.473053,4800.0,1500.0,100.0,4504.0,973.0,1.0,0.0,0.0,20.0,layer99.hdf5
10537387,-25.831062,-89.478294,4800.0,1500.0,100.0,4504.0,942.0,1.0,0.0,0.0,20.0,layer99.hdf5

### Step 2: Add in the sequence numbering

In [13]:
df = df_all.copy()
print(df.shape)

(10537388, 12)

In [14]:
# create layer feature
df['layer'] = df['file'].str.replace('layer', '')
df['layer'] = df['layer'].str.replace('.hdf5', '').astype(int)

In [15]:
display(df.head())
display(df.tail())

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file,layer
0,-18.487875,-80.184509,4800.0,1500.0,100.0,0.0,166.0,1.0,0.0,0.0,20.0,layer1.hdf5,1
1,-18.487875,-80.191986,4800.0,1500.0,100.0,1536.0,214.0,1.0,0.0,0.0,20.0,layer1.hdf5,1
2,-18.487125,-80.203217,4800.0,1500.0,100.0,3421.0,509.0,1.0,0.0,0.0,20.0,layer1.hdf5,1
3,-18.486378,-80.217072,4800.0,1500.0,100.0,4051.0,738.0,1.0,0.0,0.0,20.0,layer1.hdf5,1
4,-18.485628,-80.231659,4800.0,1500.0,100.0,4310.0,856.0,1.0,0.0,0.0,20.0,layer1.hdf5,1

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file,layer
10537383,-25.804117,-89.448349,4800.0,1500.0,100.0,4506.0,989.0,1.0,0.0,0.0,20.0,layer99.hdf5,99
10537384,-25.813473,-89.458084,4800.0,1500.0,100.0,4507.0,973.0,1.0,0.0,0.0,20.0,layer99.hdf5,99
10537385,-25.821707,-89.466316,4800.0,1500.0,100.0,4506.0,989.0,1.0,0.0,0.0,20.0,layer99.hdf5,99
10537386,-25.827694,-89.473053,4800.0,1500.0,100.0,4504.0,973.0,1.0,0.0,0.0,20.0,layer99.hdf5,99
10537387,-25.831062,-89.478294,4800.0,1500.0,100.0,4504.0,942.0,1.0,0.0,0.0,20.0,layer99.hdf5,99

In [16]:
ls_uniq = df['layer'].unique()
ls_uniq

array([  1,  10, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,  11,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119,  12, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129,  13, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139,  14, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149,  15, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159,  16, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        17, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,  18, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189,  19, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199,   2,  20, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209,  21, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219,  22, 220, 221, 222, 223, 224, 225, 226, 227,
       228, 229,  23, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
        24, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249,  25, 250,
       251, 252, 253, 254, 255, 256, 257, 258, 259,  26, 260, 261, 262,
       263, 264, 265, 266, 267, 268, 269,  27, 270, 271, 272, 273, 274,
       275, 276, 277, 278, 279,  28, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289,  29, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299,   3,  30, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309,
        31, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,  32, 320,
       321, 322, 323, 324, 325, 326, 327, 328, 329,  33, 330, 331, 332,
       333, 334, 335, 336, 337, 338, 339,  34, 340, 341, 342, 343, 344,
       345, 346, 347, 348, 349,  35, 350, 351, 352, 353, 354, 355, 356,
       357, 358, 359,  36, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369,  37, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379,  38,
        39,   4,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,   5,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,   6,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,   7,  70,  71,  72,  73,
        74,  75,  76,  77,  78,  79,   8,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,   9,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99])

In [17]:
ls_uniq.sort()
# ls_uniq[0:10]
ls_uniq

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
       352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
       365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
       378, 379])

In [18]:
df2 = []
df2 = pd.DataFrame(columns= ['x', 'y', 'NominalPower', 'NominalSpeed',
                  'NominalSpotDiameter', 'LaserPowerCurrent',
                  'SignalPdInGaAs', 'IDbulkLayer', 'IDoocLayer',
                  'c_1_cost', 'c_2_cost', 'file', 'layer', 'step'
                 ])
df2

Empty DataFrame
Columns: [x, y, NominalPower, NominalSpeed, NominalSpotDiameter, LaserPowerCurrent, SignalPdInGaAs, IDbulkLayer, IDoocLayer, c_1_cost, c_2_cost, file, layer, step]
Index: []

In [19]:
for layer in ls_uniq: #[0:10]:
    print(layer)
    df_tmp = []
    df_tmp = df[df['layer'] == layer]
    df_tmp = df_tmp.reset_index(drop=True)
    df_tmp['step'] = df_tmp.index.to_list()
    df_tmp['step'] = df_tmp['step'] + 1
    df2 = pd.concat([df2, df_tmp])

df2 = df2.reset_index(drop=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379

In [20]:
display(df2.head())
display(df2.tail())

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file,layer,step
0,-18.487875,-80.184509,4800.0,1500.0,100.0,0.0,166.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,1
1,-18.487875,-80.191986,4800.0,1500.0,100.0,1536.0,214.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,2
2,-18.487125,-80.203217,4800.0,1500.0,100.0,3421.0,509.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,3
3,-18.486378,-80.217072,4800.0,1500.0,100.0,4051.0,738.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,4
4,-18.485628,-80.231659,4800.0,1500.0,100.0,4310.0,856.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,5

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file,layer,step
10537383,-27.686602,-89.454346,4800.0,1500.0,100.0,4510.0,1086.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30744
10537384,-27.683609,-89.464073,4800.0,1500.0,100.0,4511.0,1086.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30745
10537385,-27.680988,-89.471931,4800.0,1500.0,100.0,4512.0,1046.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30746
10537386,-27.678741,-89.477173,4800.0,1500.0,100.0,4511.0,1046.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30747
10537387,-27.676123,-89.480911,4800.0,1500.0,100.0,4501.0,1124.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30748

In [21]:
df2.to_csv('data_additivemfg_LPBF_convertedtrumpfchallenge_v20230403a.csv', index=False)

### Steph 3: Verify that saved data is valid

In [22]:
df_verify = pd.read_csv('./data_out/data_additivemfg_LPBF_convertedtrumpfchallenge_v20230403a.csv')

In [23]:
print(df_verify.shape)
print(df_verify.columns)
display(df_verify.head())
display(df_verify.tail())

(10537388, 14)
Index(['x', 'y', 'NominalPower', 'NominalSpeed', 'NominalSpotDiameter',
       'LaserPowerCurrent', 'SignalPdInGaAs', 'IDbulkLayer', 'IDoocLayer',
       'c_1_cost', 'c_2_cost', 'file', 'layer', 'step'],
      dtype='object')

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file,layer,step
0,-18.487875,-80.184510,4800.0,1500.0,100.0,0.0,166.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,1
1,-18.487875,-80.191986,4800.0,1500.0,100.0,1536.0,214.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,2
2,-18.487125,-80.203220,4800.0,1500.0,100.0,3421.0,509.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,3
3,-18.486378,-80.217070,4800.0,1500.0,100.0,4051.0,738.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,4
4,-18.485628,-80.231660,4800.0,1500.0,100.0,4310.0,856.0,1.0,0.0,0.0,20.0,layer1.hdf5,1,5

,x,y,NominalPower,NominalSpeed,NominalSpotDiameter,LaserPowerCurrent,SignalPdInGaAs,IDbulkLayer,IDoocLayer,c_1_cost,c_2_cost,file,layer,step
10537383,-27.686602,-89.454346,4800.0,1500.0,100.0,4510.0,1086.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30744
10537384,-27.683609,-89.464070,4800.0,1500.0,100.0,4511.0,1086.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30745
10537385,-27.680988,-89.471930,4800.0,1500.0,100.0,4512.0,1046.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30746
10537386,-27.678741,-89.477170,4800.0,1500.0,100.0,4511.0,1046.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30747
10537387,-27.676123,-89.480910,4800.0,1500.0,100.0,4501.0,1124.0,1.0,0.0,0.0,20.0,layer379.hdf5,379,30748